apiVersion: v1
kind: Service
metadata:
  name: calibre
spec:
  type: LoadBalancer
  selector:
    app: calibre
  ports:
    - name: tcp
      protocol: TCP
      port: 8083
      targetPort: 8083
      nodePort: 30883
